import Link from "next/link";
import { CTA, ContactSection, HeroGraphic, PageShell, ProjectCard } from "./components";
import { projects, verifiedPerformance, whatsapp } from "./data";
import SelectedWorkCarousel from "./selected-work-carousel";
import ReviewsCarousel from "./reviews-carousel";

const services=[
  {icon:"shopify",title:"Shopify & e-commerce",text:"Conversion-focused stores with clear journeys, faster shopping and strong product presentation."},
  {icon:"performance",title:"Performance marketing",text:"Meta and Google campaigns managed around profitable purchases—not surface-level clicks."},
  {icon:"brand",title:"Brand & creative",text:"Premium visual systems and ad creative built to earn attention and trust."},
  {icon:"cro",title:"CRO & growth systems",text:"Data-led improvements across landing pages, offers and the full customer journey."},
];

const reviews=[
  {initials:"HE",name:"HUK Enterprises",role:"Social Media Marketing Client",quote:"Consistent engagement, real customers — our DMs were flooded with orders within 2 months."},
  {initials:"IM",name:"Infinite Mart PK",role:"Graphic Design & Ads Client",quote:"Sharp, on-brand creatives that actually worked — our CTR jumped right after switching to his designs."},
  {initials:"HA",name:"HairAgain International",role:"Shopify Store Client",quote:"Store built from scratch and generating sales since day one. Best investment we made."},
  {initials:"AW",name:"Awei Pakistan",role:"Electronics · Shopify Store & Social Media",quote:"Built our entire digital presence from zero — the credibility we gained was immediate."},
  {initials:"SC",name:"Scents by Scenterio",role:"Luxury Fragrances · Shopify & Brand Identity",quote:"A store that matches our premium identity — WhatsApp inquiries doubled in the first month."},
  {initials:"RP",name:"RefletePK",role:"Premium Products · Meta Ads · 8.02X Purchase ROAS",quote:"The documented purchase campaigns averaged 8.02X ROAS, with the strongest verified campaign reaching 10.85X."},
];

const faqs=[
  {question:"What kind of businesses do you work with?",answer:"I work with Pakistani and international ecommerce brands across beauty, electronics, fashion, lifestyle and multi-category retail."},
  {question:"Can you build a new Shopify store or improve an existing one?",answer:"Both. I can build a store from the ground up or audit and improve an existing store’s design, navigation, product presentation, mobile experience and conversion journey."},
  {question:"Do you also manage Meta and Google advertising?",answer:"Yes. Campaign work can include strategy, account structure, creative direction, testing, optimization and scaling around measurable purchases and revenue."},
  {question:"How long does a typical Shopify project take?",answer:"Timelines depend on catalogue size and scope. After the initial discussion, you receive a clear project plan, deliverables and realistic timeline before work begins."},
  {question:"Can you work with brands outside Pakistan?",answer:"Yes. I work remotely with international brands and can build localized storefront and campaign experiences for different markets and currencies."},
  {question:"How do we start?",answer:"Book a free strategy call or send your current store, goals and main challenge through the consultation form. I’ll review the context and recommend the most practical next step."},
];

function ServiceIcon({name}:{name:string}){return <span className={`service-icon ${name}`} aria-hidden="true"><svg viewBox="0 0 40 40" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{name==="shopify"&&<><path className="icon-fill" d="M10 14.5h20l-1.8 20H11.8L10 14.5Z"/><path d="M14.5 15V11a5.5 5.5 0 0 1 11 0v4"/><path d="M23.7 19.4c-1.1-.6-2.2-.9-3.4-.9-1.8 0-3 .9-3 2.2 0 3.1 6.6 2.2 6.6 6.5 0 2.5-2 4.3-5.1 4.3-1.5 0-3.1-.4-4.3-1.2"/><path d="M21 17.2 18.1 32"/></>}{name==="performance"&&<><circle className="icon-fill" cx="18" cy="21" r="12"/><circle cx="18" cy="21" r="6.5"/><circle cx="18" cy="21" r="1.8"/><path d="m23 16 10-10m0 0v7m0-7h-7"/><path d="m33 6-15 15"/></>}{name==="brand"&&<><path className="icon-fill" d="m9 30 3-10L28 4l8 8-16 16-11 2Z"/><path d="m24 8 8 8M12 20l8 8M9 30l6-2"/><path d="M7 8h6M10 5v6M29 30h6M32 27v6"/></>}{name==="cro"&&<><path className="icon-fill" d="M6 7h28L24 19v9l-8 5V19L6 7Z"/><path d="M9 33h25"/><path d="M22 29V24m5 5v-9m5 9V15"/><path d="m23 18 4-4 3 2 5-6"/></>}</svg></span>}

const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};

export default function Home(){const featured=projects.filter(p=>p.featured);return <PageShell>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
  <section className="hero hero-photo"><HeroGraphic/><div className="shell hero-grid"><div className="hero-copy">
    <div className="desktop-hero-copy"><span className="eyebrow live"><i/>Available for selected projects</span><p className="hello">Hi, I’m Amir Raza.</p><h1>I build stores<br/>&amp; run ads that <em>sell more.</em></h1><p className="lead"><b>Shopify Expert & Performance Marketer</b> helping Pakistani and international brands improve conversion and scale profitable campaigns.</p><div className="actions"><a className="button button-primary" href={whatsapp}>Book a free strategy call →</a><Link className="text-link" href="/case-studies">See verified results ↗</Link></div><div className="proof-row"><span><b>22+</b> stores</span><span><b>{verifiedPerformance.purchases}</b> purchases</span><span><b>{verifiedPerformance.averageRoas}</b> purchase ROAS</span></div></div>
    <div className="mobile-hero-copy"><span className="eyebrow mobile-hero-kicker"><i/>Ecommerce growth partner · Working worldwide</span><p className="mobile-h1" role="heading" aria-level={2}>I build stores<br/>&amp; run ads that <em>sell more.</em></p><p>Shopify stores, performance marketing and conversion systems shaped by real ecommerce experience.</p><a className="mobile-strategy-button" href={whatsapp}>Get your free strategy call <span>→</span></a><Link className="mobile-work-link" href="/portfolio">Explore our work <span>→</span></Link><p className="mobile-store-proof">22+ ecommerce stores built across 10+ industries.</p><div className="mobile-roas-card"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M6 31V8M6 31h27M11 25l7-7 6 4 9-12"/></svg><div><b>{verifiedPerformance.averageRoas}</b><span>average Purchase ROAS across verified accounts</span></div></div></div>
  </div><div className="hero-identity" aria-label="Amir Raza profile"><span>Shopify · Meta Ads · CRO</span><b>Digital Growth Specialist</b><small>Karachi, Pakistan · Working worldwide</small></div></div></section>
  <section className="trust-strip"><div className="shell"><span>Experience across</span><b>Shopify</b><b>Meta Ads</b><b>Google Ads</b><b>WooCommerce</b></div></section>
  <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Selected work</span><h2>Real stores.<br/><em>Proven outcomes.</em></h2></div><Link className="text-link" href="/portfolio">View all 24 projects →</Link></div><SelectedWorkCarousel>{featured.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</SelectedWorkCarousel></div></section>
  <section className="metric-band"><div className="shell metric-grid">{[[verifiedPerformance.spend,"verified ad spend"],[verifiedPerformance.purchases,"verified purchases"],[verifiedPerformance.averageRoas,"average Purchase ROAS"],[verifiedPerformance.highestRoas,"highest verified ROAS"]].map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</div></section>
  <section className="section soft"><div className="shell"><div className="section-head"><div><span className="eyebrow">What I do</span><h2>One partner for<br/><em>commerce growth.</em></h2></div><p className="head-copy">Store, acquisition and creative work as one connected system.</p></div><div className="service-grid">{services.map((s,i)=><article key={s.title}><div><ServiceIcon name={s.icon}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></div></section>
  <section className="section"><div className="shell about-grid"><div className="about-photo"><img src="/images/amir-hero-premium.webp" alt="Amir Raza"/><span>Karachi · Available worldwide</span></div><div><span className="eyebrow">The person behind the work</span><h2>Strategy first.<br/><em>Execution included.</em></h2><p>I help brands connect good products with the right customers through sharper stores, better creative and advertising that is accountable to revenue.</p><p>Every engagement stays hands-on—from initial diagnosis to launch and optimization.</p><Link className="text-link" href="/results">Explore the results →</Link></div></div></section>
  <section id="reviews" className="section testimonials-section"><div className="shell"><div className="centered-section-head"><span className="eyebrow">Client reviews</span><h2>What <em>clients say.</em></h2><p>Direct feedback from brands supported across stores, creative and performance marketing.</p></div><ReviewsCarousel>{reviews.map(review=><article className="testimonial-card" key={review.name}><div className="review-client"><span className="review-avatar">{review.initials}</span><div><h3>{review.name}</h3><p>{review.role}</p></div></div><div className="review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>{review.quote}</blockquote></article>)}</ReviewsCarousel></div></section>
  <section id="faqs" className="section faq-section soft"><div className="shell faq-layout"><div><span className="eyebrow">Frequently asked questions</span><h2>Clear answers.<br/><em>Before we start.</em></h2><p>Everything you need to know about Shopify, performance marketing and working together.</p></div><div className="faq-list">{faqs.map((faq,index)=><details key={faq.question} open={index===0}><summary><span>{faq.question}</span><i aria-hidden="true">+</i></summary><p>{faq.answer}</p></details>)}<a className="text-link faq-ask" href={whatsapp}>Ask another question →</a></div></div></section>
  <ContactSection/><CTA/>
 </PageShell>}
